### ISSUE TITLE
Question: should this VS Code Extension also work on Windows? / is console output possible?

### ISSUE THREAD

**Issue by SymboLinker** [vknabel/vscode-swift-coverage#1]
Hi Valentin,

Is there a way to display the result as a table as console output with columns "source file name" and "uncovered line numbers"?

I've created the repository [MathKeyboardEngine.Swift](https://github.com/MathKeyboardEngine/MathKeyboardEngine.Swift) and I would like to test with code coverage. When I run the code coverage command (in VS Code on **Windows**, Swift Coverage v1.0.1), a file 
`.build\debug\codecov\MathKeyboardEngine.json`
is generated as expected, but I don't know how to get human-readable results - it does not result in color changes in the files of the Sources folder as described in the readme.

I saw that the [Swift Development Environment](https://github.com/vknabel/vscode-swift-development-environment) is only for macOS and Linux, so I suspect that this extension also only for macOS and Linux? Anyway, getting the result as console output as described above would probably be the quickest solution if it is available. If it is not available, I will probably dive into the source code of this repository to create it :)

Thanks in advance for your answer.

Kind regards,
Symbolinker

**Comment by SymboLinker** [comment]
I've reached 100%. I'll close this issue.

**Comment by vknabel** [comment]
Hi @SymboLinker! Thanks for reaching out!
The Swift Development Environment is intentionally just for macOS and Linux. All other extensions might work on Windows, but I am not able to test it as I do not have access to a Windows installation. If you find any Windows specific bugs, feel free to report them.

Sadly I haven't got lots of time lately and wasn't able to answer or have a look on your issue.

Regarding this extension: if I remember correctly some things have changed on the side of the official swift extension in terms of generating the codecov file. I haven't had a deeper look on this and whether this extension is still needed, or if I need to adjust the docs.

I'll try to have a look on this soon. Sorry for the inconvenience.
